return {
  'h-michael/lsp-ext.nvim',
  'onsails/lspkind-nvim',
  'tpope/vim-abolish',
  'leafgarland/typescript-vim',
  'ericcurtin/CurtineIncSw.vim',
  'tpope/vim-vinegar',
  'troydm/zoomwintab.vim',
  'lukas-reineke/indent-blankline.nvim',
  'famiu/bufdelete.nvim',

  -- Eye candy,
  'vim-airline/vim-airline',
  'vim-airline/vim-airline-themes',
  'powerline/fonts',
  'sainnhe/sonokai',
  'sainnhe/edge',
  'arzg/vim-colors-xcode',
  'sickill/vim-monokai',
  'Mcmartelle/vim-monokai-bold',
  'ludovicchabant/vim-lawrencium',
  'flazz/vim-colorschemes',
  'ryanoasis/vim-devicons',
}
